"use client";
import localFont from "next/font/local";
import "./globals.css";
import { redirect, usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import "@uploadthing/react/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// const optimaLT = localFont({
//   src: "./fonts/OptimaLT.woff",
//   variable: "--font-optima-lt",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const allowedPaths = [
    "/booth/size/10x10",
    "/booth/size/10X10",
    "/booth/code/CEL101001",
    "/booth/code/CEL101002",
    "/booth/code/CEL101003",
  ];
  const currentPath = usePathname();

  if (!allowedPaths.includes(currentPath)) {
    redirect("/not-found");
  }

  return (
    <html lang="en">
      <body>
        <Toaster />
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
