export const majorExhibitingCities = [
  "Anaheim",
  "Atlanta",
  "Austin",
  "Baltimore",
  "Boston",
  "Charlotte",
  "Chicago",
  "Dallas",
  "Denver",
  "Detroit",
  "Houston",
  "Indianapolis",
  "Las Vegas",
  "Long Beach",
  "Kansas City",
  "Los Angeles",
  "Louisville",
  "Miami",
  "Milwaukee",
  "Minneapolis",
  "Nashville",
  "New Orleans",
  "New York",
  "Novi",
  "Ohio",
  "Omaha",
  "Palm Springs",
  "Orlando",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "Riverside County",
  "Rosemont",
  "Sacramento",
  "Salt Lake City",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Santa Clara",
  "Seattle",
  "South Carolina",
  "St. Louis",
  "Tampa",
  "Tennessee",
  "Utah",
  "Washington DC",
];
